### ISSUE TITLE
Content editor: Add way to mark the channel as featured

### ISSUE THREAD

**Issue by manuq** [endlessm/kolibri-dynamic-collections-plugin#11]
The editor should allow marking a channel as featured for the collection. Internally this should be a tag "featured-channel" applied to the root node.

Needed for: https://github.com/endlessm/kolibri-explore-plugin/issues/529

Here is the proposed format: https://github.com/endlessm/endless-key-collections/compare/wip-featured-channels?expand=1#diff-d74e40460fa3ad73684a58e1cffc558a2ff9139591994839148e1a6eb6ba6de1

**Comment by erikos** [comment]
The editor changes are tracked in https://github.com/endlessm/kolibri-dynamic-collections-plugin/issues/11
