### ISSUE TITLE
Release Collections Editor bulk editing update

### ISSUE THREAD

**Issue by dylanmccall** [endlessm/kolibri-dynamic-collections-plugin#17]
Let's (finally) release our Collections Editor update adding several UI enhancements as well as the ability to set tags for topic nodes.

Phabricator tasks:
- https://phabricator.endlessm.com/T34712
- https://phabricator.endlessm.com/T34512
- https://phabricator.endlessm.com/T34349
- https://phabricator.endlessm.com/T34514
- https://phabricator.endlessm.com/T34350

To do:
- [x] [Release v1.4.0 on PyPi](https://pypi.org/project/kolibri-dynamic-collections-plugin/1.4.0/)
- [x] flathub/org.learningequality.Kolibri.Plugin.kolibri-dynamic-collections-plugin#5

**Comment by erikos** [comment]
Everything is done here. Archiving.
